name: build epid-verification-service
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout scm
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: cache maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom/xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: clone epid-sdk
        uses: actions/checkout@v3
        with:
          repository: Intel-EPID-SDK/epid-sdk
          ref: v7.0.1
          path: Native/src/service/dependencies/epid-sdk
      - name: build epid-sdk
        run: |
          cd Native/src/service/dependencies/epid-sdk
          chmod +x configure
          ./configure
          make all
          make check
          make install
      - name: clone google-test
        uses: actions/checkout@v3
        with:
          repository: google/googletest
          ref: release-1.7.0
          path: Native/src/service/dependencies/googletest
      - name: build googletest
        run: |
           cd Native/src/service/dependencies/googletest/make
           make
      - name: build epid verification service
        run: |
          mvn clean install
          tar -czvf demo.tar.gz demo/
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: demo.tar.gz
          path: demo.tar.gz
